# Generated by Django 5.0.7 on 2024-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='nombreUsuario', max_length=45, unique=True)),
                ('claveusuario', models.CharField(db_column='claveUsuario', max_length=45)),
                ('nombrepersona', models.CharField(db_column='nombrePersona', max_length=45)),
                ('apellidopersona', models.CharField(db_column='apellidoPersona', max_length=45)),
                ('perfilcreado', models.IntegerField(blank=True, db_column='perfilCreado', null=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacionesempresa',
            fields=[
                ('id_evaluacionesempresa', models.AutoField(db_column='id_evaluacionesEmpresa', primary_key=True, serialize=False)),
                ('comentarioevaluador', models.TextField(blank=True, db_column='comentarioEvaluador', null=True)),
                ('puntuacionservicio', models.IntegerField(db_column='puntuacionServicio')),
                ('puntuacionproducto', models.IntegerField(db_column='puntuacionProducto')),
                ('fechaevaluacion', models.DateField(db_column='fechaEvaluacion')),
            ],
            options={
                'db_table': 'evaluacionesEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id_evaluador', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='nombreUsuario', max_length=45)),
                ('claveusuario', models.CharField(db_column='claveUsuario', max_length=45)),
                ('nombrepersona', models.CharField(db_column='nombrePersona', max_length=45)),
                ('apellidopersona', models.CharField(db_column='apellidoPersona', max_length=45)),
                ('iconoevaluador', models.CharField(blank=True, db_column='iconoEvaluador', max_length=255, null=True)),
            ],
            options={
                'db_table': 'evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fichaestadisticasempresa',
            fields=[
                ('id_fichaestadisticasempresa', models.AutoField(db_column='id_fichaEstadisticasEmpresa', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('visitastotales', models.IntegerField(blank=True, db_column='visitasTotales', null=True)),
                ('visitasinvitados', models.IntegerField(blank=True, db_column='visitasInvitados', null=True)),
                ('visitasevaluadores', models.IntegerField(blank=True, db_column='visitasEvaluadores', null=True)),
                ('cantidadcomentarios', models.IntegerField(blank=True, db_column='cantidadComentarios', null=True)),
                ('cantidadevaluaciones', models.IntegerField(blank=True, db_column='cantidadEvaluaciones', null=True)),
                ('promediopuntuacionservicio', models.DecimalField(blank=True, db_column='promedioPuntuacionServicio', decimal_places=2, max_digits=3, null=True)),
                ('promediopuntuacionproducto', models.DecimalField(blank=True, db_column='promedioPuntuacionProducto', decimal_places=2, max_digits=3, null=True)),
                ('promediocalificaciongeneral', models.IntegerField(blank=True, db_column='promedioCalificacionGeneral', null=True)),
                ('crecimientoevaluaciones', models.IntegerField(blank=True, db_column='crecimientoEvaluaciones', null=True)),
            ],
            options={
                'db_table': 'fichaEstadisticasEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galeriaempresa',
            fields=[
                ('id_galeriaempresa', models.AutoField(db_column='id_galeriaEmpresa', primary_key=True, serialize=False)),
                ('imagen1', models.CharField(max_length=255)),
                ('imagen2', models.CharField(max_length=255)),
                ('imagen3', models.CharField(max_length=255)),
                ('imagen4', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'galeriaEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horariosempresa',
            fields=[
                ('id_horarioempresa', models.AutoField(db_column='id_horarioEmpresa', primary_key=True, serialize=False)),
                ('descripcionhorario', models.CharField(db_column='descripcionHorario', max_length=60)),
                ('horarioapertura', models.TimeField(db_column='horarioApertura')),
                ('horariocierre', models.TimeField(db_column='horarioCierre')),
            ],
            options={
                'db_table': 'horariosEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfilempresa',
            fields=[
                ('id_perfilempresa', models.AutoField(db_column='id_perfilEmpresa', primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(db_column='nombreEmpresa', max_length=100)),
                ('esloganempresa', models.CharField(blank=True, db_column='esloganEmpresa', max_length=200, null=True)),
                ('descripcionempresa', models.TextField(db_column='descripcionEmpresa')),
                ('direccionempresa', models.CharField(db_column='direccionEmpresa', max_length=200)),
                ('telefonoempresa', models.CharField(db_column='telefonoEmpresa', max_length=20)),
                ('logoempresa', models.CharField(db_column='logoEmpresa', max_length=255)),
            ],
            options={
                'db_table': 'perfilEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productosempresa',
            fields=[
                ('id_productosempresa', models.AutoField(db_column='id_productosEmpresa', primary_key=True, serialize=False)),
                ('productoempresa', models.CharField(blank=True, db_column='productoEmpresa', max_length=60, null=True)),
                ('descripcionproducto', models.CharField(blank=True, db_column='descripcionProducto', max_length=255, null=True)),
            ],
            options={
                'db_table': 'productosEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redessocialesempresa',
            fields=[
                ('id_redessocialesempresa', models.AutoField(db_column='id_redesSocialesEmpresa', primary_key=True, serialize=False)),
                ('correoempresa', models.CharField(blank=True, db_column='correoEmpresa', max_length=150, null=True)),
                ('paginawebempresa', models.CharField(blank=True, db_column='paginaWebEmpresa', max_length=255, null=True)),
                ('instagramempresa', models.CharField(blank=True, db_column='instagramEmpresa', max_length=30, null=True)),
                ('facebookempresa', models.CharField(blank=True, db_column='facebookEmpresa', max_length=50, null=True)),
                ('whatsappempresa', models.CharField(blank=True, db_column='whatsappEmpresa', max_length=255, null=True)),
            ],
            options={
                'db_table': 'redesSocialesEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviciosempresa',
            fields=[
                ('id_serviciosempresa', models.AutoField(db_column='id_serviciosEmpresa', primary_key=True, serialize=False)),
                ('nombreservicio', models.CharField(db_column='nombreServicio', max_length=100)),
            ],
            options={
                'db_table': 'serviciosEmpresa',
                'managed': False,
            },
        ),
    ]
